<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="person" nsURI="http:///person" nsPrefix="person">
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_9MhOkHtZEeKpeZ-e8atWJw" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_WrwwI4GcEeK-PrTTZpW3tw" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Hm_l4IGbEeK-PrTTZpW3tw" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_2t1HUHtuEeKCCdjWtXQmoQ" name="Student" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_crhTIIGcEeK-PrTTZpW3tw" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_4lF5AHtwEeKCCdjWtXQmoQ" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
