<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scope" nsURI="http:///scope" nsPrefix="scope">
  <eClassifiers xsi:type="ecore:EClass" name="IComparisonScope" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IComparisonScope2" abstract="true" interface="true"
      eSuperTypes="#//IComparisonScope"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDiagnosable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterImpl"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractComparisonScope" abstract="true"
      eSuperTypes="#//AdapterImpl #//IDiagnosable #//IComparisonScope2"/>
  <eClassifiers xsi:type="ecore:EClass" name="FilterComparisonScope" eSuperTypes="#//AbstractComparisonScope"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultComparisonScope" eSuperTypes="#//FilterComparisonScope"/>
</ecore:EPackage>
